
GET http://localhost:5178

###
GET http://localhost:5178/api/catagories

###
POST http://localhost:5178/api/catagories
Content-Type: application/json

{
        "name":"Sports",
        "description":"Bad catagory"

}

###
DELETE http://localhost:5178/api/catagories/29d57d3e-b556-43fd-aa99-f86ee127326e

###
PUT http://localhost:5178/api/catagories/4158bdfa-3e6d-494e-8abd-386116ca8565
Content-Type: application/json

{
        "name":"Food",
        "description":"good catagory"

}
