
###
GET http://localhost:5178/v1/api/catagories

###
GET http://localhost:5178/v1/api/catagories/7c9f3983-4e7d-4616-9e62-9ee27ea4b6f8

###
POST http://localhost:5178/v1/api/catagories
Content-Type: application/json

{
        "name":"Electronics",
        "description":"Bad catagory"

}

###
DELETE http://localhost:5178/v1/api/catagories/e1170fe5-272a-4ae6-8515-1e7b9e713e8a

###
PUT http://localhost:5178/v1/api/catagories/a4842067-19e6-45c1-8ed7-70d08c0e32ea
Content-Type: application/json

{
        "name":"Clothing",
        "description":"Bad catagory"

}
